/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#FFF4F0',
          100: '#FFE4D6',
          200: '#FFC9AD',
          300: '#FFA87F',
          400: '#FF8A57',
          500: '#FF6B35',
          600: '#ED5626',
          700: '#C7441E',
          800: '#A23718',
          900: '#7D2A12',
        },
        accent: {
          50: '#FFF0F2',
          100: '#FFD6DB',
          200: '#FFADB8',
          300: '#FF8596',
          400: '#FF5470',
          500: '#FF2442',
          600: '#E61F38',
          700: '#C41A2F',
          800: '#A11526',
          900: '#7D101D',
        },
        state: {
          idea: '#9CA3AF',
          outline: '#3B82F6',
          world: '#8B5CF6',
          writing: '#FF6B35',
          review: '#F59E0B',
          publish: '#10B981',
        },
        chart: {
          1: '#FF6B35',
          2: '#FF2442',
          3: '#6366F1',
          4: '#10B981',
          5: '#F59E0B',
          6: '#3B82F6',
          7: '#8B5CF6',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          hover: '#F8F9FB',
          active: '#F0F2F5',
          sunken: '#E8EBF0',
          dark: '#1e293b',
        },
        dark: {
          bg: '#0f172a',
          surface: '#1e293b',
          text: '#e2e8f0',
        },
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #FF6B35 0%, #FF2442 100%)',
        'gradient-primary-hover': 'linear-gradient(135deg, #ED5626 0%, #E61F38 100%)',
        'gradient-primary-soft': 'linear-gradient(135deg, #FFF4F0 0%, #FFE8EC 100%)',
      },
      fontFamily: {
        sans: [
          '"PingFang SC"',
          '"Microsoft YaHei"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        serif: [
          'Georgia',
          '"Songti SC"',
          '"SimSun"',
          '"STSong"',
          'serif',
        ],
        mono: [
          '"SF Mono"',
          '"JetBrains Mono"',
          '"Menlo"',
          '"Consolas"',
          '"Courier New"',
          'monospace',
        ],
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '14px',
        xl: '20px',
        '2xl': '28px',
      },
      spacing: {
        'sidebar': '240px',
        'sidebar-collapsed': '64px',
        'context-hub': '320px',
        'editor-max': '720px',
        'container-max': '1440px',
      },
      boxShadow: {
        'primary': '0 2px 8px rgba(255,107,53,0.25)',
      },
      transitionTimingFunction: {
        'base': 'ease',
      },
      transitionDuration: {
        'fast': '100ms',
        'base': '150ms',
        'slow': '200ms',
      },
    },
  },
  plugins: [],
};
