"""baseline: SQL migrations managed by apply_migrations.py

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-09
"""
from alembic import op  # noqa: F401

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Existing deployments are upgraded by backend/apply_migrations.py, which
    # records applied SQL files in schema_migrations. This baseline reserves
    # Alembic history for future autogenerated revisions.
    pass


def downgrade() -> None:
    pass
